_wandb:
    value:
        cli_version: 0.21.3
        e:
            k6el7mth68ec0zvrbgyxxpscgkjwysdf:
                args:
                    - --use_wandb
                codePath: trainer/train_full_sft.py
                codePathLocal: train_full_sft.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "253055008768"
                        used: "52345446400"
                email: amy.xiongxu@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: 561979c7e34ed48bce320598952d892dce33ccd6
                    remote: https://github.com/jingyaogong/minimind.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-80e6a3ed-cb1b-b188-c017-dd98513feafb
                host: 8e0a91063211
                memory:
                    total: "89631739904"
                os: Linux-6.1.123+-x86_64-with-glibc2.35
                program: /content/drive/MyDrive/MA680/minimind/trainer/train_full_sft.py
                python: CPython 3.12.11
                root: /content/drive/MyDrive/MA680/minimind/trainer
                startedAt: "2025-09-11T09:31:34.716765Z"
                writerId: k6el7mth68ec0zvrbgyxxpscgkjwysdf
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 53
                - 71
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 53
                - 71
                - 105
            "3":
                - 13
            "4": 3.12.11
            "5": 0.21.3
            "6": 4.46.3
            "12": 0.21.3
            "13": linux-x86_64
